// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//  0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181.

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

let first_term = 1
let second_term = 2
let even_term_sum = 0;
function fibonacci(exceed_value)
{
    for(let n=3;n<exceed_value;n++)
    {
        let next_term = first_term+second_term
        first_term = second_term
        second_term = next_term
        if(next_term<exceed_value)
        {
            if(next_term%2==0)
            {
                even_term_sum=even_term_sum+next_term;
            }
        // console.log(next_term);
        }
    }
        console.log("the value of even terms is",even_term_sum+2);
}
fibonacci(4000000);






















// let first_term = 1
// let second_term = 2
// let value = 4000;
// let even_term_sum = 0;
// function fibonacci(position)
// {
//     // console.log(first_term)
//     // console.log(second_term)
//     for(let n=3;n<position;n++)
//     {
//         let next_term = first_term+second_term
//         first_term = second_term
//         second_term = next_term
//         if(next_term<value)
//         {
//             if(next_term%2==0)
//             {
//                 even_term_sum=even_term_sum+next_term;
//             }
//         // console.log(next_term);
//         }
//         else
//         {
//         //  console.log("value exceeds") 
//          break
//         }
//     }
//         // console.log(second_term)  
//         console.log(even_term_sum+2);
// }
// fibonacci(20)

